[versions]
kotlin = "2.4.20"
spring-boot = "4.1.1"
spring-dependency-management = "1.1.7"
springdoc = "3.1.0"
wiremock = "3.13.2"
archunit = "1.5.1"

[libraries]
springdoc-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
wiremock = { module = "org.wiremock:wiremock-standalone", version.ref = "wiremock" }
archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
